import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local';
import {cn} from "@/lib/utils";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("flex flex-col",pretendard.className)}>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
